### ISSUE TITLE
IE9 delete & tab out changes input value

### ISSUE THREAD

**Issue by lalanotlistening** [tests-always-included/angular-placeholder#9]
In IE9, on the [demo page](http://plnkr.co/edit/#!/gVo2jM244jbIvMOYZocr?p=preview), follow these steps:

1. Click in First Name (or any of the fields)
2. Type anything (I used a space)
3. Use backspace or delete to clear out the field
4. Press TAB to exit the field
5. The placeholder text will now be the field's actual value

If you click out of the field, this doesn't happen.

**Comment by fidian** [comment]
Turns out this also affected IE8.

I pushed a change that fixes it for me in my setup with IE but would like confirmation that it works for you as well.  The commit is in the issue-5 branch because there's some other updates in that branch which make this fix work a bit better.

Please test and let me know if you can find any other problems.

**Comment by fidian** [comment]
Closing due to a lack of response and confirmation in #5 that the patch appears to correct this issue as well.
